package main

import (
	"github.com/jeffersonto/feira-api/cmd/server"
	_ "github.com/jeffersonto/feira-api/docs" // docs generated by Swag CLI
	"github.com/jeffersonto/feira-api/internal/config"
	"github.com/sirupsen/logrus"
)

// @contact.name   Jefferson de Almeida Costa
// @contact.url    https://www.linkedin.com/in/jeffersonacosta/
// @contact.email  jefferson.acosta@hotmail.com

// @host      localhost:8080
// @BasePath  /v1

// @title           Feira API
// @version         1.0
// @description     Gerenciamento de feiras livres de São Paulo
// @termsOfService  http://swagger.io/terms/
func main() {
	config.Start()
	port := "8080"

	if err := server.Run(port); err != nil {
		logrus.Errorf("error running server: %+v", err)
	}
}
